// PrivacyPolicy.js
import React from 'react';

const PrivacyPolicy = () => {
    return (
        <div className="min-h-screen  md:p-10 border-gray-800 flex flex-col justify-center items-center bg-gray-100 text-gray-900">
            <div className="bg-white rounded-lg border-4 border-gray-800 shadow-lg max-w-screen  w-full ">
                <div className="p-6">
                    <h2 className="text-2xl font-semibold text-center mb-4 bg-orange-500 text-white py-2 px-4 rounded-lg">Privacy Policy</h2>
                    <p className="text-sm mb-6">
                        <strong>Effective Date:</strong> July 1st 2024 (07/01/2024) <br />
                        <strong>Shop at Banau</strong> ("we," "us," or "our") operates the shopatbanau.com website (hereinafter referred to as the "Service"). This Privacy Policy explains how we collect, use, disclose, and protect information that applies to our Service, and your choices about the collection and use of your information.
                    </p>
                    <div className="mb-6">
                        <h3 className="text-lg font-semibold mb-2 bg-orange-500 text-white py-2 px-4 rounded-lg">Chapter 1: Introduction</h3>
                        <p className="text-sm">
                            <strong>1.1 Overview</strong><br />
                            This Privacy Policy outlines the types of information we collect, how we use it, and the steps we take to ensure that your information is protected. It applies to all users of our Service.
                        </p>
                        <p className="text-sm mt-2">
                            <strong>1.2 Authorization to Contact</strong><br />
                            By using our Website and/or registering at shopatbanau.com, you authorize us to contact you via email, phone call, or SMS to offer our services and transaction receipts  amd provide product knowledge
                        </p>
                        <p className="text-sm mt-2">
        <strong>2.3 Data Collection and Usage Disclaimer</strong><br />
        We are committed to ensuring that your personal data is collected and used responsibly. We will only collect personal data that you provide to us through the input fields on our Service or third party cookies that you've volunteeringly have acknowledged. We will not misuse this data in any way. All data collected will be used solely for the purposes stated in this policy and to improve your experience with our Service.
    </p>
                    </div>
                    <div className="mb-6">
    <h3 className="text-lg font-semibold mb-2 bg-orange-500 text-white py-2 px-4 rounded-lg">Chapter 2: Personal Data</h3>
    <p className="text-sm">
        <strong>2.1 Personal Data</strong><br />
        Personal Data means any information about a living individual who can be identified, directly or indirectly, from that information. This includes, but is not limited to, information such as your name, email address, phone number, postal address, IP address, and any other details you provide to us when using our Service. Personal Data can also include information that is linked to your account, such as transaction history, preferences, and interactions with our Service.
    </p>
    <p className="text-sm mt-2">
        <strong>2.2 Usage Data</strong><br />
        Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself. This data may include information such as:
    </p>
    <ul className="list-disc list-inside pl-4">
        <li>Your computer's Internet Protocol address (e.g., IP address)</li>
        <li>Browser type and version</li>
        <li>The pages of our Service that you visit</li>
        <li>The time and date of your visit</li>
        <li>The time spent on those pages</li>
        <li>Unique device identifiers</li>
        <li>Other diagnostic data</li>
    </ul>
    <p className="text-sm mt-2">
        <strong>2.3 Data Collection and Usage Disclaimer</strong><br />
        We are committed to ensuring that your personal data is collected and used responsibly. We will only collect personal data that you provide to us through the input fields on our Service. We will not misuse this data in any way. All data collected will be used solely for the purposes stated in this policy and to improve your experience with our Service.
    </p>
</div>
                    <div className="mb-6">
                        <h3 className="text-lg font-semibold mb-2 bg-orange-500 text-white py-2 px-4 rounded-lg">Chapter 3: Information We Collect and Its Use</h3>
                        <p className="text-sm">
                            <strong>3.1 Information You Provide Us Directly</strong><br />
                            While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. This information may include:
                        </p>
                        <ul className="list-disc list-inside pl-4">
                            <li>Email Address</li>
                            <li>Phone Number</li>
                            <li>Business Name</li>
                            <li>Business Location</li>
                            <li>First and Last Name</li>
                            <li>Cookies and Usage Data</li>
                        </ul>
                        <p className="text-sm mt-2">
                            <strong>3.2 Usage Data</strong><br />
                            We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device. This Usage Data may include information such as:
                        </p>
                        <ul className="list-disc list-inside pl-4">
                            <li>Your computer's Internet Protocol address (e.g., IP address)</li>
                            <li>Browser type and version</li>
                            <li>The pages of our Service that you visit</li>
                            <li>The time and date of your visit</li>
                            <li>The time spent on those pages</li>
                            <li>Unique device identifiers</li>
                            <li>Other diagnostic data</li>
                        </ul>
                        <p className="text-sm mt-2">
                            <strong>3.3 Cookies Information</strong><br />
                            We use cookies and similar tracking technologies to track the activity on our Service and hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies such as beacons, tags, and scripts are also used to collect and track information and to improve and analyze our Service.
                        </p>
                    </div>
                    <div className="mb-6">
                        <h3 className="text-lg font-semibold mb-2 bg-orange-500 text-white py-2 px-4 rounded-lg">Chapter 4: Purpose of Information Use</h3>
                        <p className="text-sm">
                            <strong>4.1 Providing and Maintaining Our Service</strong><br />
                            We use the information we collect to provide and maintain our Service, ensuring it functions correctly and efficiently.
                        </p>
                        <p className="text-sm mt-2">
                            <strong>4.2 Participation in Interactive Features</strong><br />
                            To allow you to participate in interactive features of our Service when you choose to do so.
                        </p>
                        <p className="text-sm mt-2">
                            <strong>4.3 Customer Support</strong><br />
                            To provide customer support and respond to your inquiries and requests.
                        </p>
                        <p className="text-sm mt-2">
                            <strong>4.4 Analysis and Improvement</strong><br />
                            To gather analysis or valuable information that helps us improve our Service.
                        </p>
                        <p className="text-sm mt-2">
                            <strong>4.5 Monitoring Usage</strong><br />
                            To monitor the usage of our Service and ensure proper functioning.
                        </p>
                        <p className="text-sm mt-2">
                            <strong>4.6 Detecting and Addressing Technical Issues</strong><br />
                            To detect, prevent, and address technical issues that may arise.
                        </p>
                        <p className="text-sm mt-2">
                            <strong>4.7 Communications and Marketing</strong><br />
                            To provide you with news, special offers, and general information about other goods, services, and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information.
                        </p>
                    </div>
                    <div className="mb-6">
                        <h3 className="text-lg font-semibold mb-2 bg-orange-500 text-white py-2 px-4 rounded-lg">Chapter 5: Data Retention</h3>
                        <p className="text-sm">
                            <strong>5.1 Retention Period for Personal Data</strong><br />
                            Shop at Banau will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
                        </p>
                        <p className="text-sm mt-2">
                            <strong>5.2 Retention Period for Usage Data</strong><br />
                            Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or when we are legally obligated to retain this data for longer time periods.
                        </p>
                    </div>
                    <div className="mb-6">
                        <h3 className="text-lg font-semibold mb-2 bg-orange-500 text-white py-2 px-4 rounded-lg">Chapter 6: Transfer of Data</h3>
                        <p className="text-sm">
                            <strong>6.1 International Data Transfers</strong><br />
                            Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
                        </p>
                        <p className="text-sm mt-2">
                            <strong>6.2 Consent to Transfer</strong><br />
                            Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer. Shop at Banau will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy, and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
                        </p>
                    </div>
                    <div className="mb-6">
                        <h3 className="text-lg font-semibold mb-2 bg-orange-500 text-white py-2 px-4 rounded-lg">Chapter 7: Deletion of Data</h3>
                        <p className="text-sm">
                            <strong>7.1 Account Deletion</strong><br />
                            You can request the deletion of your Personal Data directly by deleting your account within your Account section on our website.
                        </p>
                        <p className="text-sm mt-2">
                            <strong>7.2 Contact for Deletion</strong><br />
                            If you are unable to perform this action yourself, you can contact us at shopatbanau@gmail.com to request the deletion of your Personal Data.
                        </p>
                    </div>
                    <div className="mb-6">
                        <h3 className="text-lg font-semibold mb-2 bg-orange-500 text-white py-2 px-4 rounded-lg">Chapter 8: Sharing Your Information</h3>
                        <p className="text-sm">
                            <strong>8.1 Business Transactions</strong><br />
                            If Shop at Banau is involved in a merger, acquisition, or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.
                        </p>
                        <p className="text-sm mt-2">
                            <strong>8.2 Disclosure for Law Enforcement</strong><br />
                            Under certain circumstances, Shop at Banau may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency).
                        </p>
                        <p className="text-sm mt-2">
                            <strong>8.3 Legal Requirements</strong><br />
                            Shop at Banau may disclose your Personal Data in the good faith belief that such action is necessary to:
                        </p>
                        <ul className="list-disc list-inside pl-4">
                            <li>Comply with a legal obligation.</li>
                            <li>Protect and defend the rights or property of Shop at Banau.</li>
                            <li>Prevent or investigate possible wrongdoing in connection with the Service.</li>
                            <li>Protect the personal safety of users of the Service or the public.</li>
                            <li>Protect against legal liability.</li>
                        </ul>
                    </div>
                    <div className="mb-6">
                        <h3 className="text-lg font-semibold mb-2 bg-orange-500 text-white py-2 px-4 rounded-lg">Chapter 9: Data Security</h3>
                        <p className="text-sm">
                            <strong>9.1 Security Measures</strong><br />
                            The security of your data is important to us. We strive to use commercially acceptable means to protect your Personal Data.
                        </p>
                        <p className="text-sm mt-2">
                            <strong>9.2 Limitations of Security</strong><br />
                            However, remember that no method of transmission over the Internet or method of electronic storage is 100% secure, and we cannot guarantee its absolute security.
                        </p>
                    </div>
                    <div className="mb-6">
                        <h3 className="text-lg font-semibold mb-2 bg-orange-500 text-white py-2 px-4 rounded-lg">Chapter 10: Protection of Children's Information</h3>
                        <p className="text-sm">
                            <strong>10.1 Protection of Children's Information</strong><br />
                            Shop at Banau does not knowingly collect or solicit personal information from children under the age of 18. The Service and its content are not directed at children under the age of 18. In the event that we learn that we have collected personal information from a child under age 18 without verification of parental consent, we will delete that information promptly. If you believe that we might have any information from or about a child under 18, please contact us at shopatbanau@gmail.com.
                        </p>
                        <p className="text-sm mt-2">
                            <strong>10.2 Reporting and Deletion</strong><br />
                            Parents or legal guardians who believe that Shop at Banau might have any information about a child under 18 can contact us at shopatbanau@gmail.com to request the review, deletion, or restriction of the child's information.
                        </p>
                    </div>
                    <div className="mb-6">
                        <h3 className="text-lg font-semibold mb-2 bg-orange-500 text-white py-2 px-4 rounded-lg">Chapter 11: Updates to This Privacy Policy</h3>
                        <p className="text-sm">
                            <strong>11.1 Notification of Changes</strong><br />
                            We will notify you via email and/or a prominent notice on our Service before any changes to this Privacy Policy become effective.
                        </p>
                        <p className="text-sm mt-2">
                            <strong>11.2 Effective Date of Changes</strong><br />
                            Changes to this Privacy Policy are effective when they are posted on this page. Please review this Privacy Policy periodically for updates.
                        </p>
                    </div>
                </div>
                {/* <div className="bg-gray-200 px-6 py-4 rounded-b-lg flex justify-center">
                    <button className="bg-[#FF7C1D] text-white px-6 py-3 rounded-lg hover:bg-[#FFA06D]">Close</button>
                </div> */}
            </div>
        </div>
    );
};

export default PrivacyPolicy;
